#pragma once

// Do not edit this file.
// This file is automatically generated from modes.xml.
// Any changes will be lost.
//
enum imagingMode
{
    UnknownMode = -1,
    StartMode = 0,

    BMode = 0,
    MMode = 1,
    ColourMode = 2,
    PwMode = 3,
    TriplexMode = 4,
    PanoMode = 5,
    DualMode = 6,
    QuadMode = 7,
    CompoundMode = 8,
    DualColourMode = 9,
    DualCompoundMode = 10,
    CwMode = 11,
    ColorSplitMode = 12,
    F4DMode = 13,
    TriplexCwMode = 14,
    ColourMMode = 15,
    ElastoMode = 16,
    AnatomicalMMode = 17,
    ElastoComparativeMode = 18,
    FusionMode = 19,
    VecDopMode = 20,
    BiplaneMode = 21,
    FibroMode = 22,
    SURFMode = 23,
    Reslice3DMode = 24,

    EndMode // the last one 
};
